spring:
  application:
    name: MedAgend
  datasource:
    url: jdbc:postgresql://ep-snowy-union-a44oqiqa.us-east-1.aws.neon.tech/medagend?sslmode=require
    username: medagend_owner
    password: Ywvk13NCDyEu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
